import { Medico, Especialidad } from "@/types";

export const MOCK_ESPECIALIDADES: Especialidad[] = [
  { id: "ESP001", nombre: "Medicina General", descripcion: "Consulta general y preventiva" },
  { id: "ESP002", nombre: "Cardiología", descripcion: "Enfermedades del corazón y sistema cardiovascular" },
  { id: "ESP003", nombre: "Pediatría", descripcion: "Medicina infantil" },
  { id: "ESP004", nombre: "Ginecología", descripcion: "Salud femenina y reproductiva" },
  { id: "ESP005", nombre: "Traumatología", descripcion: "Lesiones del sistema musculoesquelético" },
  { id: "ESP006", nombre: "Odontología", descripcion: "Salud bucal y dental" },
  { id: "ESP007", nombre: "Nutrición", descripcion: "Orientación nutricional y dietética" },
];

export const MOCK_MEDICOS: Medico[] = [
  {
    id: "MED001",
    nombre: "Carlos",
    apellido: "Rodríguez",
    especialidadId: "ESP001",
    especialidadNombre: "Medicina General",
    turno: "MANANA",
    cubiculo: "01",
    telefono: "0414-1234567",
    email: "carlos.rodriguez@mercal.gob.ve",
    activo: true,
    diasLaborables: [1, 2, 3, 4, 5],
    horaInicio: "08:00",
    horaFin: "12:00",
  },
  {
    id: "MED002",
    nombre: "Ana",
    apellido: "Martínez",
    especialidadId: "ESP002",
    especialidadNombre: "Cardiología",
    turno: "MANANA",
    cubiculo: "02",
    telefono: "0424-2345678",
    email: "ana.martinez@mercal.gob.ve",
    activo: true,
    diasLaborables: [1, 3, 5],
    horaInicio: "08:00",
    horaFin: "12:00",
  },
  {
    id: "MED003",
    nombre: "José",
    apellido: "Hernández",
    especialidadId: "ESP003",
    especialidadNombre: "Pediatría",
    turno: "TARDE",
    cubiculo: "03",
    telefono: "0416-3456789",
    email: "jose.hernandez@mercal.gob.ve",
    activo: true,
    diasLaborables: [2, 4],
    horaInicio: "13:00",
    horaFin: "17:00",
  },
  {
    id: "MED004",
    nombre: "Gabriela",
    apellido: "López",
    especialidadId: "ESP004",
    especialidadNombre: "Ginecología",
    turno: "MANANA",
    cubiculo: "04",
    telefono: "0412-4567890",
    email: "gabriela.lopez@mercal.gob.ve",
    activo: true,
    diasLaborables: [1, 2, 3, 4, 5],
    horaInicio: "08:00",
    horaFin: "14:00",
  },
  {
    id: "MED005",
    nombre: "Fernando",
    apellido: "Torres",
    especialidadId: "ESP005",
    especialidadNombre: "Traumatología",
    turno: "TARDE",
    cubiculo: "05",
    telefono: "0426-5678901",
    email: "fernando.torres@mercal.gob.ve",
    activo: false,
    diasLaborables: [3, 5],
    horaInicio: "13:00",
    horaFin: "17:00",
  },
  {
    id: "MED006",
    nombre: "Sofía",
    apellido: "Ramírez",
    especialidadId: "ESP006",
    especialidadNombre: "Odontología",
    turno: "MANANA",
    cubiculo: "06",
    telefono: "0414-6789012",
    email: "sofia.ramirez@mercal.gob.ve",
    activo: true,
    diasLaborables: [1, 2, 4],
    horaInicio: "08:00",
    horaFin: "12:00",
  },
  {
    id: "MED007",
    nombre: "Ricardo",
    apellido: "Moreno",
    especialidadId: "ESP007",
    especialidadNombre: "Nutrición",
    turno: "TARDE",
    cubiculo: "07",
    telefono: "0424-7890123",
    email: "ricardo.moreno@mercal.gob.ve",
    activo: true,
    diasLaborables: [1, 5],
    horaInicio: "14:00",
    horaFin: "18:00",
  },
];
